### ISSUE TITLE
Steve returns HttpStatus.UNAUTHORIZED when ChargeBoxId is not allowed to connect

### ISSUE THREAD

**Issue by tintigx** [steve-community/steve#1020]
Hi,

#### Checklist

- [X] I checked other issues already, but found no answer/solution
- [X] I checked the documentation and wiki, but found no answer/solution
- [ ] I am running the latest version and the issue still occurs
- [X] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.5.0
Operating system  : W10
JDK               : ...
Database          : ...
```

#### Expected Behavior

According to "Open Charge Point Protocol JSON1.6, OCPP-J 1.6 Specification" if the Central System does not recognize the charge point identifier in the URL path, it SHOULD send an HTTP response with status 404 and abort the WebSocket connection as described in [RFC6455].

#### Actual Behavior

Steve returns HttpStatus.UNAUTHORIZED = 401

See OcppWebSocketHandshakeHandler.java 
if (!allowConnection) {
    log.error("ChargeBoxId '{}' is not recognized.", chargeBoxId);
    response.setStatusCode(HttpStatus.UNAUTHORIZED);
    return false;
}

The OCPP Spec indicates that the Central System SHOULD return 404, why does Steve returns 401 ?

**Comment by goekay** [comment]
good catch, fixing it. thanks!
