### ISSUE TITLE
Unable to add a charge point using curl 

### ISSUE THREAD

**Issue by Chabanee** [steve-community/steve#1054]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.5.0
Operating system  : linux
JDK               : ...
Database          : ...
```

#### Expected Behavior

Give a solution to add a chargepoint using curl (ps: I'm using php).

#### Actual Behavior

Nothing

#### Steps to Reproduce the Problem

  1. Using a syntax to add a chargepoint with my script php or terminal. 
  2. Get no response.

#### Additional context

I'm also wondering what is the meanning of "dquote>" if you can help me.

<img width="224" alt="Capture d’écran 2023-02-10 141959" src="https://user-images.githubusercontent.com/73824189/218102047-529a5e50-1123-41d9-8c15-fa78faa5ba9e.png">

**Comment by juherr** [comment]
There is no api for that. See #1000

**Comment by Chabanee** [comment]
Thanks for your answer,

but is there any way else to do that in php ?

**Comment by juherr** [comment]
Yes. Not recommended but you can use pdo, connect to the database and add the expected entries in the appropriate tables.

**Comment by Chabanee** [comment]
If you can explain me how please it will be really helpeful.

Thanks

**Comment by juherr** [comment]
If you don't know, it will be too complicate.
Just wait for the expected api and you'll be able to use curl then.

**Comment by Chabanee** [comment]
Alright, thank you.

Last question can I use php to connect to the database and add the expected entries in the appropriate tables ?

**Comment by Chabanee** [comment]
oK thanks
