### ISSUE TITLE
webapi.key blocking custom api

### ISSUE THREAD

**Issue by rdc-Green** [steve-community/steve#1064]
We already have an api in place that is no longer working with the new api functionality that has been added to steve. Is there any way to disable the new functionality so that our api is not blocked?

**Comment by juherr** [comment]
Or you can propose your changes into a PR, expect it will be merged and replace the usage of your api by the official one.

**Comment by goekay** [comment]
what is the problem? why is it blocked? as long as the apis are sitting at different context paths they should not interfere with each other. 

for the record, the new apis are at `../api/v1/..`

**Comment by rdc-Green** [comment]
We're bypassing api security for custom api url. Thank you for your help
