### ISSUE TITLE
built steve sucessfuly in maven but unable to run it  ,generates a log with error

### ISSUE THREAD

**Issue by rathourcode** [steve-community/steve#1122]

**Comment by goekay** [comment]
no context, no details. closing it.

**Comment by rathourcode** [comment]
i am trying use steve for ocpp1.6 protocol for electric vehicles. i am sucessful in building steve using maven but i am unable to run it.it generates a log file for error.
[git.txt](https://github.com/steve-community/steve/files/11239583/git.txt)

**Comment by goekay** [comment]
solution: https://github.com/steve-community/steve/wiki/FAQ#how-to-fix-the-exception-mysql-and-java-are-not-using-the-same-time-zone
