### ISSUE TITLE
unable to connect to steve server 

### ISSUE THREAD

**Issue by rathourcode** [steve-community/steve#1132]
steves log suggests
de.rwth.idsg.steve.ocpp.ws.OcppWebSocketHandshakeHandler - No protocol (OCPP version) is specified.

**Comment by juherr** [comment]
What is the Steve issue here and what is your expectation?
If the station doesn't send the version, check there 😉

**Comment by rathourcode** [comment]
> What is the Steve issue here and what is your expectation? If the station doesn't send the version, check there 😉

hai juherr 
i am testing my steve web server , i succesfuly connected to it using postman using my local device but when i try from different device i am unable to connect to it .
i have blocked my firewalls, i have used the local ip in my websocket url what can be the possible reason for error

**Comment by rathourcode** [comment]
please helppppppppp

**Comment by chandan-ultraviolette** [comment]
@rathourcode  how you connected with postman ? I am trying below but facing the issue

![image](https://github.com/steve-community/steve/assets/126255050/ebba9e94-bf83-4938-ab0d-797d5c3109d6)
