### ISSUE TITLE
About API and WebSocket

### ISSUE THREAD

**Issue by 01mk027** [steve-community/steve#1149]
Hi admins and programmers;
For a week (maybe much more than i think), i'm trying to fire Steve's websocket mechanism by sending request to API of Steve. I want to send message with Steve's native Websocket mechanism. Because, a charge point listen only one address, that is like ws://127.0.0.1:8080/steve/websocket/CentralSystemService/WS002 and i need to send and receive messages by help of API. Is it possible? If it's not, how i can achieve? Any idea is pretty.

**Comment by 01mk027** [comment]
Actually, i want to send ReserveNow request from API to station.

**Comment by juherr** [comment]
There is currently no API in Steve to interact with a station. See #1000

**Comment by 01mk027** [comment]
> There is currently no API in Steve to interact with a station. See #1000

thanks juherr
