### ISSUE TITLE
Steve's API and Transactions

### ISSUE THREAD

**Issue by 01mk027** [steve-community/steve#1154]
In #1149 i asked question and received back. But, i realized that, i forgot to explain about all details.

In Steve, under the page of http://127.0.0.1:8080/steve/manager/operations/v1.6/{transactionName}, we can select station and connector than we can send message to the station in OCPP format.

Similarly, i want to send message from Steve's API to websocket clients with Steve's own websocket service which is specific for device. (Indeed, I want to send message to a charge point (websocket client) from the address of ws://127.0.0.1:8080/steve/websocket/CentralSystemService/(chargeBoxId) via Steve's API. Charge box id is written into database.)

Is it possible? If yes, how it can be achieved? Which library or libraries help me? Thanks in advance.

**Comment by goekay** [comment]
this is still not possible. the same feedback to #1149 is valid here as well.
