### ISSUE TITLE
java -jar steve.jar not running

### ISSUE THREAD

**Issue by DvlprSG** [steve-community/steve#1168]
When i am trying to run the steve.jar file, i am getting below mentioned error:

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
$ java -jar target/steve.jar 

Log file: /home/lenovo/logs/steve.log
Starting..................... FAILED!
Please refer to the log file for details
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

And I mentioned the logs in the below lines:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

[INFO ] 2023-06-06 15:35:33,187 de.rwth.idsg.steve.utils.PropertiesFileLoader - Hint: The Java system property 'main.properties' can be set to point to an external properties file, which will be prioritized over the bundled one
[INFO ] 2023-06-06 15:35:33,309 de.rwth.idsg.steve.Application - Loaded the properties. Starting with the 'PROD' profile
[INFO ] 2023-06-06 15:35:33,325 de.rwth.idsg.steve.Application - Date/time zone of the application is set to UTC. Current date/time: 2023-06-06T10:05:33.315Z
[INFO ] 2023-06-06 15:35:33,592 org.eclipse.jetty.server.Server - jetty-10.0.11; built: 2022-06-21T21:12:44.640Z; git: d988aa016e0bb2de6fba84c1659049c72eae3e32; jvm 11.0.19+7-post-Ubuntu-0ubuntu120.04.1
[INFO ] 2023-06-06 15:35:33,907 org.eclipse.jetty.server.handler.ContextHandler.steve - No Spring WebApplicationInitializer types detected on classpath
[INFO ] 2023-06-06 15:35:33,916 org.eclipse.jetty.server.session.DefaultSessionIdManager - Session workerName=node0
[INFO ] 2023-06-06 15:35:33,932 org.eclipse.jetty.server.handler.ContextHandler.steve - Initializing Spring root WebApplicationContext
[INFO ] 2023-06-06 15:35:33,933 org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
[INFO ] 2023-06-06 15:35:34,823 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[ERROR] 2023-06-06 15:35:35,923 com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jooq.DSLContext]: Factory method 'dslContext' threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

[INFO ] 2023-06-06 15:35:35,973 org.eclipse.jetty.server.Server - Stopped Server@2453f95d{STOPPING}[10.0.11,sto=5000]
[INFO ] 2023-06-06 15:35:35,978 org.eclipse.jetty.server.Server - Shutdown Server@2453f95d{STOPPING}[10.0.11,sto=5000]
[INFO ] 2023-06-06 15:35:35,999 org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@6063d80a{/steve,jar:file:/home/lenovo/Sanava/ocpp/steVe/steve-steve-3.5.0/target/steve.jar!/webapp,STOPPED}

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
What can i do to solve this error? If any one faced this issue please help 

I am using ubuntu linux 20.04 LTS

**Comment by juherr** [comment]
Your database is not responding.
Check the database logs and you should be able to understand what is the problem

**Comment by ridamnibjia** [comment]
@DvlprSG Try raising the [max_allowed_packet](http://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_max_allowed_packet) to a much larger number, since the default is 1M. I would suggest about 10 times the largest TEXT or BLOB field you have in your current dataset.

To set the max_allowed_packet to 256M, you can add it to /etc/my.cnf or my.ini

```
[mysqld]
max_allowed_packet=256M
```
to cover future restarts of mysqld. To install the value now on the server, please run this:

`SET GLOBAL max_allowed_packet = 1024 * 1024 * 256;`

Give it a try.

**Comment by goekay** [comment]
i assume this issue to be resolved, and am closing it.
