### ISSUE TITLE
Charging Profile accepted but still drawing current way more than the set limit

### ISSUE THREAD

**Issue by justarandomnerd** [steve-community/steve#1192]
So I have a charger, I set a ChargePointMaxProfile, it was accepted, I set a TxDefaultProfile, it was accepted, I turned on a transaction, hooked up the charger to a couple resistors and set a TxProfile which was accepted. But the charger output is a current value that was set in neither of these. 
For example I set the ChargePointMaxProfile limit as 15 A
TxDefaultProfile limit as 10 A
TxProfile limit as 7 A
But the output of the charger is 12 A

**Comment by fnkbsi** [comment]
Steve sends the Profiles and the EVSE/Chargebox accepts it. In that case, it's seems not to be an issue of Steve, it an issue of your EVSE respectively EV.

Steve is connected with the EVSE over OCPP and provieds the profile, but does not monitor it. The AC-EVSE communicates with the EV over SAE J1772 or IEC 61851 (PWM signal) protocol. The Duty-Cycle of the PWM represents the maximum current the EV is allowed to consume. In this whole System the EV is responsible to limit the current. Your "EV" is just a couple of resistors? If you want to know if your EVSE is working correctly, you have to measure the Duty-Cycle of the PWM between CP-Pin and PE. 

Hope this helps.
