### ISSUE TITLE
Remove firstArrivingMeterValueIfMultiple

### ISSUE THREAD

**Issue by goekay** [steve-community/steve#1209]
#### Checklist

- [x] I checked other issues already and found no answer
- [x] I checked the documentation and found no answer
- [x] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

I think this flag/feature is causing more harm than good. We should maybe question the _added value_ of having it. 

#### Describe alternative solutions or features you've considered 

There are PRs that address the issues such as https://github.com/steve-community/steve/pull/1013 and https://github.com/steve-community/steve/pull/1164

#### Describe the solution you'd like

I am inclined to remove it altogether (instead of fixing it) and return the raw data from the table. Fixing it means adding more code that would make a complicated part even more complicated. Therefore, I ask the authors of these PRs and the wider community for their feedback.

#### Additional context

- https://github.com/steve-community/steve/issues/1004

**Comment by fnkbsi** [comment]
With the current implementation, the reduction of MeterValues is not important.
However, two potential new features could benefit from this:
- Export of transaction details / MeterValues as CSV (works also without a "data reduction")
- Visualization of the transaction / charging process using SVG graphics

What I definitely don't need is the data reduction with the last arriving MeterValue (firstArrivingMeterValueIfMultiple == false).
