### ISSUE TITLE
question - Remote Start Transaction

### ISSUE THREAD

**Issue by andreschinchilla81** [steve-community/steve#1211]
To start a remote transaction, is it necessary to indicate the connector? If I do not indicate it, it returns the status "Rejected"

**Comment by juherr** [comment]
The rejection comes from the station. You should check there if you see something.

What is your station (vendor, model, firmware version)?

**Comment by andreschinchilla81** [comment]
![image](https://github.com/steve-community/steve/assets/137243776/7211c2cc-e9cc-4a98-b0e0-97171ee4263a)
configured as follows:
![image](https://github.com/steve-community/steve/assets/137243776/c6cc0f8e-8820-4b5f-856f-8353dc6fbaed)
![image](https://github.com/steve-community/steve/assets/137243776/908d2d64-4cf5-443d-a106-4907d8e33c5a)

**Comment by juherr** [comment]
I confirm what I previously said: the rejection comes from the station.

See the ocpp 1.6 specifications:
![image](https://github.com/steve-community/steve/assets/254697/6b5be2ac-63e4-4853-bd5c-992669baff1d)

You should ask vendor support if it is supposed to work.

**Comment by goekay** [comment]
hey @andreschinchilla81 may i ask why you reopened this ticket? can this be considered as done? or is something missing?

**Comment by andreschinchilla81** [comment]
> hey @andreschinchilla81 may i ask why you reopened this ticket? can this be considered as done? or is something missing?

Sorry, my bad!

**Comment by andreschinchilla81** [comment]
Sorry for reopening the topic, it is only to indicate that the problem occurs in SteVe because when sending the request without a specific connector, an empty connector is sent and as such our load centers (magnumcap) expect it as connector = 0. Modify that part in my copy of the code and it works perfect
