### ISSUE TITLE
Allow All OCPP TAGS

### ISSUE THREAD

**Issue by jot4p** [steve-community/steve#1245]
Hi,
I have some EV chargers and multiple tags.

It's possible to allow always any type of tag ? Any user with compatible RF card (tag) can charge the vehicle!

**Comment by juherr** [comment]
Why do you use tag if every one is free to charge? 
Why not configuring your charger into a plug-n-charge mode where it will send a default tag value configured in steve?

**Comment by jot4p** [comment]
Hi Juherr ,
How I can adjust my charger to plug and charge mode ? That is the question :)

**Comment by juherr** [comment]
You should provide the manifacturer, model and firmware version of your charger.

But nobody can replace the official support and you should start with them.

**Comment by jot4p** [comment]
Hi juherr

I thought it was a parameter that I could send via ocpp /STEVE

![image](https://github.com/steve-community/steve/assets/15892047/e99b22f1-535f-4eab-a99f-bce9df707d21)

**Comment by goekay** [comment]
i dont think there is an out of the box feature in ocpp standard that will provide this. AFAIK though. i might have a blind spot.

what you can do is (with implementation effort): always react to authorize requests with "Accepted" for every incoming id tag.

**Comment by juherr** [comment]
> I thought it was a parameter that I could send via ocpp /STEVE

Maybe an ocpp key exists to configure the charger but again you should ask to the charger manifacturer.

From [the datasheet](https://circontrol.com/datasheets/evolvesmart-eng.pdf):
![image](https://github.com/steve-community/steve/assets/254697/796d3925-a17b-41fc-8656-74f2850cae86)

What you are asking for sounds like the "Connect 'n' Charge" mode.

**Comment by jot4p** [comment]
Ok, 
Instead of use Open Access , maybe I need to develop a APP to request charging activation..  What is the best way to create the app, based on Steve Websocket ?

**Comment by juherr** [comment]
You'll have to find where is the authorization logic and replace it by your own.

**Comment by fnkbsi** [comment]
An alternativ to @juherr suggestion is to add the OCPP operations "Remote Start Transaction" and "Remote Stop Transaction" to the WebApi. Then you can use the steve web interface for your APP.

**Comment by juherr** [comment]
Yes, see #1000

**Comment by goekay** [comment]
i consider the issue resolved, since multiple solution approaches have been suggested even though steve does not support this out of the box. this is a too nuanced feature to implement globally in steve. there are many use cases. @jot4p wants all tags to be allowed at all stations. what if some other user wants all tags to be allowed at _some_ stations? etc.
