### ISSUE TITLE
Cannot Unlock Charger When It's Connected to Steve

### ISSUE THREAD

**Issue by xiaojieTao** [steve-community/steve#1256]
I connected my Wallbox Pulsar Plus charger to Steve OCPP and the charger turned itself to 'Locked' status and I can't figure out how to unlock it. I tried 'Unlock Connector' operation in Steve and the response from charger is 'NotSupported'. I think this operation is to unlock any physical connector retention lock and my charger doesn't have one. I browsed the Wallbox documentations and I found these words in [this page](https://support.wallbox.com/en/knowledge-base/ocpp-activation-and-setup-guide/):

_Unlocking a charger
When your charger is connected via OCPP to your CSMS, users will be able to unlock the charger by:
Using an RFID card
Introducing a PIN code (Commander 2 only)_

However, my model (Pulsar Plus) doesn't have a RFID reader and therefore neither of the option works. How can I unlock the charger?

**Comment by juherr** [comment]
That's a question for the support of pulsar.

Maybe try to do it via the mobile app.
Or https://support.wallbox.com/en/knowledge-base/how-to-restore-your-charger/

**Comment by xiaojieTao** [comment]
> That's a question for the support of pulsar.
> 
> Maybe try to do it via the mobile app. Or https://support.wallbox.com/en/knowledge-base/how-to-restore-your-charger/

I contacted Wallbox customer service and they told me that once the charger is connected to OCPP, the OCPP backend is responsible for unlocking the charger. Is there any feature or operation in Steve related to unlocking a charger?

**Comment by goRaspy** [comment]
Try change availability ocpp command

**Comment by juherr** [comment]
> I contacted Wallbox customer service and they told me that once the charger is connected to OCPP, the OCPP backend is responsible for unlocking the charger. Is there any feature or operation in Steve related to unlocking a charger?

Ask them what is the expected ocpp request and we will be able to say how to produce it.

**Comment by goekay** [comment]
i think the wording "unlock" might be unfortunate here which leads you to a certain path.

@xiaojieTao what you want is probably _Remote Start Transaction_: you want to remotely authorize a user to charge since there is no other option (i.e. rfid card).

**Comment by xiaojieTao** [comment]
Fix: It turned out that Remote Start Transaction is the expected OCPP operation and it can 'unlock' the charger.
Appreciate the comments above!!
