### ISSUE TITLE
Can't build SteVe

### ISSUE THREAD

**Issue by warukunaiyone** [steve-community/steve#1261]
I have followed the steps. But stuck on Build (SteVe 3.6.0)
System Requirements (Installed)

- JDK 11
- Maven 3.9.4
- MariaDB 10.5

I have created a database, changed the Timezone and made changes in main.properties
when cd to steve and run mvn package

![image](https://github.com/steve-community/steve/assets/146056025/c296f131-0508-456d-86f6-e735d5806fb8)

and when run mvn flyway:repair

![image](https://github.com/steve-community/steve/assets/146056025/e82dbd86-5eda-4e74-9243-91890834457f)

Am I missing something?

**Comment by juherr** [comment]
What is the command line you ran?

**Comment by warukunaiyone** [comment]
> What is the command line you ran?
I just edited a post. Please check.

**Comment by juherr** [comment]
You miss to pass the database properties: `-Ddb.xxx=yyy`

**Comment by warukunaiyone** [comment]
> You miss to pass the database properties: `-Ddb.xxx=yyy`

Where should I fix it?

**Comment by warukunaiyone** [comment]
> you should figure out why `mvn package` fails in the first place. i have a feeling that it is because of mariadb 10.5.X you are using. mariadb introduced some breaking changes in recent versions. i dont know which patch version X you are using but i would suggest to stick to one of the tested-and-working versions: `'mariadb:10.4.30', 'mariadb:10.5.21', 'mariadb:10.6.14'`
> 
> that aside, `mvn flyway:repair` fails because properties from the properties file of the env are not available. in order to make them available you need to add initialize as first command, as in `mvn initialize flyway:repair`. this will fix the property problem, but you will probably still fail to because of the first paragraph. try to pin the mariadb version.

Thanks for the answer, I'll try it.

**Comment by warukunaiyone** [comment]
> you should figure out why `mvn package` fails in the first place. i have a feeling that it is because of mariadb 10.5.X you are using. mariadb introduced some breaking changes in recent versions. i dont know which patch version X you are using but i would suggest to stick to one of the tested-and-working versions: `'mariadb:10.4.30', 'mariadb:10.5.21', 'mariadb:10.6.14'`
> 
> that aside, `mvn flyway:repair` fails because properties from the properties file of the env are not available. in order to make them available you need to add initialize as first command, as in `mvn initialize flyway:repair`. this will fix the property problem, but you will probably still fail to because of the first paragraph. try to pin the mariadb version.

When I switched to MariaDB version 10.4.30 I was able to build and run it. Thank you very much for your help.
