### ISSUE TITLE
MaxEVCurrentOffered doesn't appear in Get Configuration or Change Configuration

### ISSUE THREAD

**Issue by PiliCano99** [steve-community/steve#1272]
Hi!

I'm using SteVE with my Charger Point and I want to change the "MaxEVCurrentOffered" but it doesn't appear as an option in the operation "Change Configuration" for OCPP 1.6. 

I have noticed that in the operation "Get Configuration"  doesn't appear too but if I do the operation "Get Configuration"  without select any of the options it returns the "MaxEVCurrentOffered".

I would like to know if "MaxEVCurrentOffered" can be modified with other OCPP operation or if  you can´t do it with SteVE.

Thanks in advance.

**Comment by goekay** [comment]
this key seems to outside of the ocpp standard, and therefore specific to your charger. you can use custom keys with "Change Configuration".

github issues are not a platform for customer support.
