### ISSUE TITLE
steve app goes down after a while

### ISSUE THREAD

**Issue by gnanasekarprakash** [steve-community/steve#1274]
#### Checklist

- [ x] I checked other issues already, but found no answer/solution
- [ x] I checked the documentation and wiki, but found no answer/solution
- [ x] I am running the latest version and the issue still occurs
- [ x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : ...3.6.0
Operating system  : ... AWS Lightsail - Ubuntu 18
JDK               : ...
Database          : ... AWS MySQL database (5.7.43)
```

#### Expected Behavior

The app should run continuously.

#### Actual Behavior

The app shutdown automatically after 5 minutes.

**Comment by fnkbsi** [comment]
Ubuntu 18? Seems little bit old.

Can you provide a log from steve
