### ISSUE TITLE
Use Charger in Open Access Mode

### ISSUE THREAD

**Issue by xiaojieTao** [steve-community/steve#1285]
How do I use a charger in Open Access Mode when it's connected to Steve OCPP? I want people to be able to just plug their car and start charging. Is there a feature in Steve or OCPP that enables that? Or is it requires more configuration that is specific to a charger model?

Charger model I have is Wallbox Pulsar Plus (U.S. version which does not have RFID reader).

**Comment by goekay** [comment]
related: https://github.com/steve-community/steve/issues/1245

there is no feature in steve for this. afaik, ocpp does not define some flows for this specific use case either. some chargers might handle and allow this internally (not my area of knowledge). or, you can make this work by tweaking the implementation of steve in some specific areas.
