### ISSUE TITLE
Transaction Wh limit

### ISSUE THREAD

**Issue by kassymbekoff** [steve-community/steve#1303]
Hello everyone! Thanks for your project! It helps me a lot.
I have one not solved issue:
Can OCPP protocol limit Wh of current transaction? 
Example:
Customer ordered 10KWh, and when Wh reached 10KWh I send RemoteStopTransaction request. 
Can charger do it by itself? Because while we stopping it at 10KWh, charger could charge more than customer order.
Can you help me with it?

P.S. Sorry for my english and hello from Kazakhstan! )

**Comment by goekay** [comment]
the building blocks are there in ocpp, and hence this is technically possible. but it is not there out-of-the-box in steve. you can extend steve to listen to MeterValues messages and if a certain amount is reached send a RemoteStopTransaction.
