### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by exel261** [steve-community/steve#1317]
Hello,
I'm using Steve version 3.4.5 on Debian. I want to update to the latest version 3.6.0. How should I update?
Thank you

**Comment by fnkbsi** [comment]
It depends on the actual configuration and system, but the basic steps are:
- Make a backup (see the wiki how to backup the database)
- update the source code
- adapt the config-file (passwords, ports, ...)
- stop Steve
- compile the source code 
- start Steve

**Comment by goekay** [comment]
@fnkbsi is right.

we try to make version updates seamless without breaking changes. 

- DB migrations are part of build. the migration scripts themselves are careful enough to migrate data (if needed at all). 
- if we change the source code, we aim for the changes to be backwards compatible.

therefore, in short: you should be able to just download the source code, build and start the app.

**Comment by brusilva84** [comment]
what about upgrading a docker installation ? what's the process for it?

**Comment by goekay** [comment]
the same. all relevant business data are in database (and the data of the database is being stored in docker volume. so, nothing to worry. your data will be there as long as you do not delete the volume). 

if you did not modify the source code, there is nothing special to do. pull the changes from upstream repo. shut down your docker instance, start the instance again using docker compose. that's it.
