### ISSUE TITLE
Looking for a vehicle identification number (vim) in OCPP

### ISSUE THREAD

**Issue by kibeki** [steve-community/steve#1320]
Hi,
is there any chance to get the vehicle identification number of the charging ev from SteVe?

**Comment by kibeki** [comment]
I found the following in https://cdn.vector.com/cms/content/products/vcharm/docs/WhitePaper_Identification_of_ElectricVehicles_in_CSMS_via_OCPP.pdf: 

```
The vehicle is identified based on the EVCC ID. The ISO15118 defines the EVCC ID as the MAC address of the EVCC 
``` 

Is this something that is also stored in SteVe data sets?

**Comment by goekay** [comment]
ISO15118 has this feature, and ocpp 2.0 (i think) has support for ISO15118. ocpp 2.0 is not implemented in steve and this is currently not possible.
