### ISSUE TITLE
Smart Charging functionalities

### ISSUE THREAD

**Issue by MadLamprey** [steve-community/steve#1327]
Hello! Can someone give a general workflow of how SteVe can be used to implement smart charging?

TIA

**Comment by LydiaBenaida** [comment]
Hello,
POV:
How to use smartcharging on steve

1. implements your ChargingProfiles : **TxProfiles** and **TxDefaultProfiles** 
2. Use **setChargingProfile** to change the state of your charge point 
3. check on part tasks : if the profile was exepted or not (accept,reject,other response)
4. Use **clearChargingProfile** to clear this profile 
5. you can even make automatic changes using those two funcionnalities on your code

Hope my answer will help you...
