### ISSUE TITLE
Where is the log folder / files using docker-compose? 

### ISSUE THREAD

**Issue by jot4p** [steve-community/steve#1328]
#### Checklist

- [ x] I checked other issues already, but found no answer/solution
- [ x] I checked the documentation and wiki, but found no answer/solution
- [ x] I am running the latest version and the issue still occurs
- [ ]x I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : docker-compose
Operating system  : ubuntu

#### Expected Behavior
where is the folder ?

**Comment by juherr** [comment]
Please, explain the question/issue.

**Comment by goekay** [comment]
docker-compose uses [the docker application profile](https://github.com/steve-community/steve/blob/master/Dockerfile#L24) which activates [these configs](https://github.com/steve-community/steve/tree/master/src/main/resources/config/docker) which means [CONSOLE as logger](https://github.com/steve-community/steve/blob/master/src/main/resources/config/docker/log4j2.xml#L9-L11).

there is no log file. we log to stdout.

**Comment by jot4p** [comment]
Ok, maybe is more easy to expose my problem..

I'm trying to add a new "Z-BOX charger", very similar to BENY charger:
https://www.beny.com/product-item/22kw-dual-socket-smart-ev-charger/

 I configured ocpp 1.6j for steve and receive on the screen : "starting session on the server with SUC" 
 
The connection is established but I don't see any "new" device in my list of chargers (unknown list) .. 

Any Idea ?  

LOG in portainer:  This is the full log ? 

![image](https://github.com/steve-community/steve/assets/15892047/2ec188cf-503e-47a9-84dc-e6ffc2c60da2)

**Comment by goekay** [comment]
your problems seem to be specific to you and your station. sorry but this has nothing to do with steve. github issues are not a platform for customer service. closing the issue.
