### ISSUE TITLE
Implementation of SteVe as a library for PLC

### ISSUE THREAD

**Issue by MadLamprey** [steve-community/steve#1332]
This might be beyond the scope of the forum but I am required to develop SteVe into a library that can be mounted onto a PLC. If anyone has any ideas on how I could achieve that, looking forward to your responses.

**Comment by MadLamprey** [comment]
Basically, either Steve functions as a standalone library, or it communicates with the PLC through Modbus. I am fairly new to Modbus and do not know how SteVe can be made to communicate through Modbus.

**Comment by goekay** [comment]
this is indeed beyond the scope of github issues. github issues are not a platform for customer service.
