### ISSUE TITLE
new producer to kindly add PEVC2107 

### ISSUE THREAD

**Issue by gitgian74** [steve-community/steve#1336]
#### Checklist

- [x ] I checked other issues already and found no answer
- [x ] I checked the documentation and found no answer
- [x ] I am running the latest version and the feature i am requesting is not implemented there

#### wants to add chargepoint Pilot&Piwin (https://www.piwinenergy.com/ev-charger-electric-car-charger-for-home/), PEVC2107 , charging station firmware version don't know, SteVe version 3.6.0 , OCPP 1.6 (e.g. OCPP1.5S), status , not working.

...

#### Describe the solution you'd like

...

#### Describe alternative solutions or features you've considered 

![IMG_0159](https://github.com/steve-community/steve/assets/122522479/bc897508-b27a-4952-9ea7-56efd2e461d5)
...

#### Please help me to understand 

...

**Comment by fnkbsi** [comment]
The charger must support OCPP.
