### ISSUE TITLE
DataTransferRequest

### ISSUE THREAD

**Issue by smdkhalifa7** [steve-community/steve#1362]
#### Checklist

- [x] I checked other issues already and found no answer
- [x] I checked the documentation and found no answer
- [x] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

I'm using steve for testing as a server for  my OCPP.
but instead of the available parameters in Data transfer operation, I needed to add some other parameters.
for that, I'm unable to find the DataTransferRequest class java  file.

...

#### Describe the solution you'd like
fetch where this DataTransferRequest class/file is located ?
and the functions associated with the parameters of that class.
...

#### Describe alternative solutions or features you've considered 
I've tried making changes in .xml file but I'm not able access where the associated functions are being implemented.
...

#### Additional context
i need to where the functions like withMessageId(), withvendorId() are defined/implemented
...

**Comment by goekay** [comment]
you want to make changes to the source code, but you struggle with it. i assume that some fundamental java knowledge missing. github issues are not a platform for these kind of questions. i would suggest to google for learning material about modern java development, maven and spring framework.
