### ISSUE TITLE
Unknown Tags

### ISSUE THREAD

**Issue by rdc-Green** [steve-community/steve#1372]
Is it possible to delete unkown tags directly from the database rather than having to select them individually through the UI? I cannot see a table anywhere in stevedb, but wanted to see if they are stored somewhere I can't see.

**Comment by goekay** [comment]
they are not stored in a database. they are kept in memory. so they are there as long as the application steve runs. they will be gone after a restart.

**Comment by rdc-Green** [comment]
Thanks @goekay appreciate the support as always!
