### ISSUE TITLE
wrong port number in readme

### ISSUE THREAD

**Issue by jovrstra** [steve-community/steve#1383]
Very small issue:
The readme file on line 137 (First Steps) refers to port 8080 rather than 8180.
:-)

**Comment by juherr** [comment]
@jovrstra Why not fix it in a pull request?

**Comment by jovrstra** [comment]
Not sure how to do it that way.... I haven't used Github that much. :-)

**Comment by juherr** [comment]
https://docs.github.com/en/get-started/start-your-journey/hello-world is a good start.

**Comment by jovrstra** [comment]
I'm not planning to develop, I don't need to pull the repository and create a branch... I just needed to install SteVe (in Docker) and wanted to inform about a small thing in the readme.

**Comment by juherr** [comment]
In that case, just go to https://github.com/steve-community/steve/blob/master/README.md and click on
![image](https://github.com/steve-community/steve/assets/254697/b22e9392-4f0f-4a24-be7e-2d23fa464a54)

**Comment by jovrstra** [comment]
Also requires me to fork it...
Let's just drop it... I just wanted to help.
