### ISSUE TITLE
OCPP 2.0.1 support

### ISSUE THREAD

**Issue by Javadevopsfs** [steve-community/steve#1399]
#### Checklist

do you have any timeline/ plans for ocpp2.0.1 integration?

- [x] I checked other issues already and found no answer
- [x] I checked the documentation and found no answer
- [x] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

...

#### Describe the solution you'd like

...

#### Describe alternative solutions or features you've considered 

...

#### Additional context

...

**Comment by goekay** [comment]
no. nothing changed, since last time this was asked :)

https://github.com/steve-community/steve/issues/779 and https://github.com/steve-community/steve/issues/513
