### ISSUE TITLE
Kafka Integration

### ISSUE THREAD

**Issue by mks1991** [steve-community/steve#1464]
I want to integrate with Kafka for performing all OCPP command and received meter values.

**Comment by goekay** [comment]
sure, please go ahead then.

what is your issue or request with us?

**Comment by ManojRailbit** [comment]
I want manage web sockets and perform all OCPP commands using kafka.

**Comment by juherr** [comment]
Steve does not function as an OCPP gateway. 
I recommend referring to the GitHub repository at https://github.com/aws-samples/aws-ocpp-gateway and adapting your code to use Kafka instead of MQTT.
