### ISSUE TITLE
Approval request: steve logo variation and placement

### ISSUE THREAD

**Issue by gruselhaus** [steve-community/steve#1465]
Hi guys,

We would like to use SteVe for a large deployment with EV stations at our headquarters and would be happy if we could refer to you. We would like to add a SteVe plot to the Mennekes station but can only plot an all black version. Can you approve the logo version and placement?

Thank you very much for your work,

Nico

<img width="971" alt="SCR-20240530-tzdb" src="https://github.com/steve-community/steve/assets/33380107/be1b8c3c-7a0e-4a8d-89da-855ce23376d3">

(Original image: https://www.roenne-technik.de/media/de/marke_hersteller_produkte/mennekes/neuheiten/amedio-professional/csm_mennekes_work_dsf7129_72e03854aa.jpg)

**Comment by goekay** [comment]
hey there, thank for getting in touch for that kind of a request, and wanting to add the logo to the chargers! this never really happens (really).

i can approve the colors and the placement of the logo. 

and again, thanks.

**Comment by gruselhaus** [comment]
Thank you 🙏

**Comment by goekay** [comment]
pls post photos of chargers (if you are allowed) with logos when they are deployed :) this is a rare occurrence.

**Comment by gruselhaus** [comment]
will do
