### ISSUE TITLE
Multiple Webusers login 

### ISSUE THREAD

**Issue by nimraidris** [steve-community/steve#1491]
I added a new user's username and password using the database and enabled the authority, but I am unable to log in with this user. I can only log in with the auth.user and auth.password mentioned in the main properties. However, I can see my new web user in Data Management > Web Users.

**Comment by fnkbsi** [comment]
Are you revering to the pull request #1165 (web user  sound like that) or steve master? 
For the PR:  Use SteVe (additional sites are part of the PR) to add the web user, because only a hash of the password will saved.

**Comment by nimraidris** [comment]
I created a new user through Steve still it's not working I already followed the steps given in #1165.

![Screenshot 2024-06-19 163923](https://github.com/steve-community/steve/assets/172633041/08085bc1-4fec-453d-9d64-a60ef2b5f65d)

![Screenshot 2024-06-19 164152](https://github.com/steve-community/steve/assets/172633041/7c4f34ce-94ac-4cb2-9ddf-988f292efc24)

**Comment by fnkbsi** [comment]
It works on my system, so I don't  know what's happening on your system.

The DB migration script should have create an webuser 'admin' with the password 'pass'. Did this webuser exist and could you enter the websites with those credentials? 

Your first webuser seems to have a short password entry. Can you enter the website with those credentials?

**Comment by nimraidris** [comment]
@fnkbsi Yeah, it works for me I deleted the target and reinstall again, and I used #1165 as mentioned.

**Comment by goekay** [comment]
closing the issue, since it looks like resolved.
