### ISSUE TITLE
Mark the most recent release as latest

### ISSUE THREAD

**Issue by Smoerrebroed** [steve-community/steve#1536]
#### Checklist

- [x] I checked other issues already and found no answer
- [x] I checked the documentation and found no answer
- [x] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

The repo page shows version 3.5.1 as the latest, but there are actually more recent releases available. It's not immediately visible which version is "the best" or "the most stable".

#### Describe the solution you'd like

Use the "latest" tag for "the one to use" and mark the most recent major release/the most recent patch release as "latest".

#### Describe alternative solutions or features you've considered 

...

#### Additional context

Not so much a feature request but even less of a bug report ... Is there a particular reason why 3.7.1 is not marked as "latest" at the moment?

**Comment by goekay** [comment]
sorry for the confusion, fixed.

> Is there a particular reason why 3.7.1 is not marked as "latest" at the moment?

the order in which i released was... 3.7.1, then 3.6.1 and then 3.5.1. therefore, github ordered them by date i guess and rightfully so. i just labeled 3.7.1 as latest.
