### ISSUE TITLE
While installing : Unable to obtain connection from database 

### ISSUE THREAD

**Issue by aatronics** [steve-community/steve#636]
When I run the below command I get "build failed message", anyone
![steveServerError](https://user-images.githubusercontent.com/25177416/127774817-4a0a8cfa-9c59-4576-ab55-b2e8710f0bc8.JPG)
![steveServerError](https://user-images.githubusercontent.com/25177416/127774836-03d5d140-fb25-46fd-9287-276b7acd87bb.JPG)
 can please help me to run the service

export MAVEN_OPTS="-Xmx100m" && mvn package

**Comment by csamsel** [comment]
The error indicates that the password or username is not correct.

**Comment by aatronics** [comment]
> The error indicates that the password or username for the database is not correct.

I have used the same username and password to create the database, also I have crosscheck the username and password on Connection details (AWS database).
is this issue will be related to timezone, because whenever I will try to open SSH from the browser, I am not able to connect to Ubuntu VPS, so always I use putty SSH to connect

**Comment by cyrilfr** [comment]
I have the same issue using Docker. In my case, the IP used to connect to the DB is the SteVe's Docker IP instead of the `db.ip` value set in the docker configuration file.

**Comment by joseapdmota** [comment]
Hi Guys,
Just run into this issue.

How did you overcome?

I'm using the docker method.

Thanks

**Comment by LivingWithHippos** [comment]
My error was editing the `main.properties` file under the `prod` folder instead of `docker`
