### ISSUE TITLE
sql replication

### ISSUE THREAD

**Issue by rishabhmehandru** [steve-community/steve#739]
Hi

I tried to set sql replication for stevedb to be able to create a backup database in case if computer crash but steve wouldn't start once I changed bind-address in "/etc/mysql/mysql.conf.d/mysqld.cnf" file. Any experience in setting up backup for stevedb will be greatly appreciated.

Best

**Comment by goekay** [comment]
this topic is about database administration, and therefore is not directly related to steve. there must be many many resources online how to do this.
