### ISSUE TITLE
Maven not build steve

### ISSUE THREAD

**Issue by glconceicao** [steve-community/steve#74]
When i build steve with maven, this erros occur.

[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< de.rwth.idsg:steve >-------------------------
[INFO] Building steve 3.0.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ steve ---
[INFO] 
[INFO] --- cxf-codegen-plugin:3.2.4:wsdl2java (generate-sources) @ steve ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.794 s
[INFO] Finished at: 2018-07-03T10:18:15-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.cxf:cxf-codegen-plugin:3.2.4:wsdl2java (generate-sources) on project steve: Execution generate-sources of goal org.apache.cxf:cxf-codegen-plugin:3.2.4:wsdl2java failed: Failed to generate types.: /home/pi/steve-steve-3.0.2/target/generated-sources/ocpp/cs/_2015/_10/AuthorizationStatus.java (No such file or directory) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

anyone knows to fix this?

**Comment by goekay** [comment]
does it help to change your steve directory name? for example, rename it from `steve-steve-3.0.2` to something shorter like `st` to see if it works. i had problems with jaxb generation (which cxf-codegen plugin triggers) depending on the directory path length (too long paths are problem, but sometimes too short ones are, too).

**Comment by glconceicao** [comment]
i did, but still it continues with the same error

**Comment by glconceicao** [comment]
sorry for my lack of knowledge, i'm begnner on raspberry. 

i'm tried install nexus respository but i could not. how can i install and compile package as dependency from nexus? has a link for following?

**Comment by goekay** [comment]
you do not have to do anything different. just pull the git repo and build steve with maven as usual.

**Comment by glconceicao** [comment]
continue with error.

i put steve repo on /home/git, and build.
i add git on steve repo and build. 

but both not build.

i think that the maven is not has permission to access the folder, and create authorization.Status.java

**Comment by goekay** [comment]
sorry but i cannot help you any further.
