### ISSUE TITLE
Community feedback wanted: Transfer of the project

### ISSUE THREAD

**Issue by goekay** [steve-community/steve#827]
Hey all,

SteVe started its life when i was a research assistant at RWTH University in the research group IDSG part of the chair Informatik 5. Hence, https://github.com/RWTH-i5-IDSG as the owner organisation. However, since mid-2019 I am no more associated with the university and the research group. Keeping the project and repository under the umbrella of RWTH-i5-IDSG has some drawbacks:
- It gives the false impression that the project is still actively developed within the university and research group.
- My former colleagues from my former research group receive e-mails with questions and inquiries. As a result, they have to deal with this unnecessary overhead.

I am actively thinking about creating a new organisation as the owner of SteVe, and asking my former colleagues to transfer the repository. This would be the new home for the future.

Feedback and ideas are welcome. Are you okay with this? Do you have alternative suggestions?

**Comment by csamsel** [comment]
(y) i think that makes sense

**Comment by mosea3** [comment]
yes, that makes sense

**Comment by mhei** [comment]
Makes sense, go for it.

**Comment by gsvitak** [comment]
Makes sense go for it.

**Comment by goekay** [comment]
thanks everyone for the input and support. the transfer happened. the new organisation is https://github.com/steve-community

github redirects links coming from old org to the new org.
