### ISSUE TITLE
Charge Point Configuration

### ISSUE THREAD

**Issue by KareemKelgamal** [steve-community/steve#873]
After setting Charge point and ChargeBoxID, I couldn't find it at operations so I can't select it for setting ConnecterID and other OCPP version.
![OCP](https://user-images.githubusercontent.com/110460484/183874754-173af877-457d-4e0b-9158-394c104260e4.PNG)

**Comment by goekay** [comment]
after registering a charging station at steve, you should also configure the station to communicate with steve.

the station informs steve about the connectors etc.

**Comment by KareemKelgamal** [comment]
Thanks @goekay 
but I'm still working on system simulation and I use steve with OCPP simulator

**Comment by goekay** [comment]
> I use steve with OCPP simulator

well, in that case, i don't know how to help you.

**Comment by KareemKelgamal** [comment]
Ok Mr. @goekay 
I have few questions
1-how can i reset the data showed at steve, I can delete charge points and other information but OCPP tags remains!?
2-Is there any way to change the user & password for steve as after I made my configurations in main properties file, it still opens with the default user name and password.

**Comment by goekay** [comment]
> 1-how can i reset the data showed at steve, I can delete charge points and other information but OCPP tags remains!?

please explore the pages under "data management". you can see/update/delete entities.

> 2-Is there any way to change the user & password for steve as after I made my configurations in main properties file, it still opens with the default user name and password.

if you change something within the properties file, you need to build and start the project again.
