### ISSUE TITLE
Not working application, POM problem

### ISSUE THREAD

**Issue by snabo1988** [steve-community/steve#881]
#### Checklist

- [* ] I checked other issues already, but found no answer/solution
- [ *] I checked the documentation and wiki, but found no answer/solution
- [ *] I am running the latest version and the issue still occurs
- [ *] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.9
Operating system  : SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux
JDK               : ...
Database          : ...
```

#### Expected Behavior

...

#### Actual Behavior
app_1  | 2022/08/23 13:45:01 Waiting for: tcp://mariadb:3306
app_1  | 2022/08/23 13:45:01 Connected to tcp://mariadb:3306
app_1  | [INFO] Scanning for projects...
app_1  | Downloading from central: https://repo1.maven.org/maven2/org/springframework/spring-framework-bom/5.3.18/spring-framework-bom-5.3.18.pom
app_1  | Downloading from JitPack: https://jitpack.io/org/springframework/spring-framework-bom/5.3.18/spring-framework-bom-5.3.18.pom
app_1  | Downloading from central: https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-bom/2.17.2/log4j-bom-2.17.2.pom
app_1  | Downloading from JitPack: https://jitpack.io/org/apache/logging/log4j/log4j-bom/2.17.2/log4j-bom-2.17.2.pom
app_1  | [ERROR] [ERROR] Some problems were encountered while processing the POMs:
app_1  | [ERROR] Non-resolvable import POM: Could not transfer artifact org.springframework:spring-framework-bom:pom:5.3.18 from/to central (https://repo1.maven.org/maven2): repo1.maven.org: Temporary failure in name resolution @ line 459, column 25
app_1  | [ERROR] Non-resolvable import POM: Could not transfer artifact org.apache.logging.log4j:log4j-bom:pom:2.17.2 from/to central (https://repo1.maven.org/maven2): repo1.maven.org: Temporary failure in name resolution @ line 466, column 25
app_1  | [ERROR] 'dependencies.dependency.version' for org.springframework:spring-webmvc:jar is missing. @ line 537, column 21
app_1  | [ERROR] 'dependencies.dependency.version' for org.springframework:spring-websocket:jar is missing. @ line 552, column 21
app_1  | [ERROR] 'dependencies.dependency.version' for org.apache.logging.log4j:log4j-core:jar is missing. @ line 568, column 21
app_1  | [ERROR] 'dependencies.dependency.version' for org.apache.logging.log4j:log4j-api:jar is missing. @ line 572, column 21
app_1  | [ERROR] 'dependencies.dependency.version' for org.apache.logging.log4j:log4j-slf4j-impl:jar is missing. @ line 576, column 21
app_1  | [ERROR] 'dependencies.dependency.version' for org.apache.logging.log4j:log4j-web:jar is missing. @ line 580, column 21
app_1  | [ERROR] 'dependencies.dependency.version' for org.springframework:spring-test:jar is missing. @ line 678, column 21
app_1  |  @ 
app_1  | [ERROR] The build could not read 1 project -> [Help 1]
app_1  | [ERROR]   
app_1  | [ERROR]   The project de.rwth.idsg:steve:3.4.9 (/code/pom.xml) has 9 errors
app_1  | [ERROR]     Non-resolvable import POM: Could not transfer artifact org.springframework:spring-framework-bom:pom:5.3.18 from/to central (https://repo1.maven.org/maven2): repo1.maven.org: Temporary failure in name resolution @ line 459, column 25: Unknown host repo1.maven.org: Temporary failure in name resolution -> [Help 2]
app_1  | [ERROR]     Non-resolvable import POM: Could not transfer artifact org.apache.logging.log4j:log4j-bom:pom:2.17.2 from/to central (https://repo1.maven.org/maven2): repo1.maven.org: Temporary failure in name resolution @ line 466, column 25: Unknown host repo1.maven.org: Temporary failure in name resolution -> [Help 2]
app_1  | [ERROR]     'dependencies.dependency.version' for org.springframework:spring-webmvc:jar is missing. @ line 537, column 21
app_1  | [ERROR]     'dependencies.dependency.version' for org.springframework:spring-websocket:jar is missing. @ line 552, column 21
app_1  | [ERROR]     'dependencies.dependency.version' for org.apache.logging.log4j:log4j-core:jar is missing. @ line 568, column 21
app_1  | [ERROR]     'dependencies.dependency.version' for org.apache.logging.log4j:log4j-api:jar is missing. @ line 572, column 21
app_1  | [ERROR]     'dependencies.dependency.version' for org.apache.logging.log4j:log4j-slf4j-impl:jar is missing. @ line 576, column 21
app_1  | [ERROR]     'dependencies.dependency.version' for org.apache.logging.log4j:log4j-web:jar is missing. @ line 580, column 21
app_1  | [ERROR]     'dependencies.dependency.version' for org.springframework:spring-test:jar is missing. @ line 678, column 21
app_1  | [ERROR] 
app_1  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
app_1  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
app_1  | [ERROR] 
app_1  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
app_1  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
app_1  | [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
steve-steve-349_app_1 exited with code 1

...

#### Steps to Reproduce the Problem

  1. ...
  2. ...
  3. ...

#### Additional context
Hello all, one day my Steve doenst start and I have that information. Someone can help? Whats wrong?

**Comment by goekay** [comment]
`Unknown host repo1.maven.org: Temporary failure in name resolution`

this not a POM problem. the computer you are building steve at cannot access the maven host. therefore, it cannot download some dependencies. please check your networking.
