### ISSUE TITLE
Unable to Reach the WebSocket on Chrome as a client after Steve Starts  -SteVe Version : 3.4.5 Operating system : Ubutnu 20.04 JDK : OpenJDK 11.0.15 Database : MariaDB 10.3.34

### ISSUE THREAD

**Issue by FlextronEV** [steve-community/steve#898]
INFO ] 2022-09-05 14:55:03,203 de.rwth.idsg.steve.utils.PropertiesFileLoader - Hint: The Java system property 'main.properties' can be set to point to an external properties file, which will be prioritized over the bundled one
[INFO ] 2022-09-05 14:55:03,615 de.rwth.idsg.steve.Application - Loaded the properties. Starting with the 'PROD' profile
[INFO ] 2022-09-05 14:55:03,691 de.rwth.idsg.steve.Application - Date/time zone of the application is set to UTC. Current date/time: 2022-09-05T14:55:03.645Z
[INFO ] 2022-09-05 14:55:04,609 org.eclipse.jetty.server.Server - jetty-10.0.7; built: 2021-10-06T19:34:02.766Z; git: da8a4553af9dd84080931fa0f8c678cd2d60f3d9; jvm 11.0.16+8-post-Ubuntu-0ubuntu120.04
[INFO ] 2022-09-05 14:55:05,557 org.eclipse.jetty.server.handler.ContextHandler.steve - No Spring WebApplicationInitializer types detected on classpath
[INFO ] 2022-09-05 14:55:05,711 org.eclipse.jetty.server.session.DefaultSessionIdManager - Session workerName=node0
[INFO ] 2022-09-05 14:55:05,769 org.eclipse.jetty.server.handler.ContextHandler.steve - Initializing Spring root WebApplicationContext
[INFO ] 2022-09-05 14:55:05,770 org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
[INFO ] 2022-09-05 14:55:08,575 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[INFO ] 2022-09-05 14:55:09,244 com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@22dc59b2
[INFO ] 2022-09-05 14:55:09,249 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[INFO ] 2022-09-05 14:55:17,414 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2010/08/}CentralSystemService from class ocpp.cs._2010._08.CentralSystemService
[INFO ] 2022-09-05 14:55:19,146 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemServiceOCPP12
[INFO ] 2022-09-05 14:55:19,185 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2012/06/}CentralSystemService from class ocpp.cs._2012._06.CentralSystemService
[INFO ] 2022-09-05 14:55:19,404 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemServiceOCPP15
[INFO ] 2022-09-05 14:55:19,407 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2015/10/}CentralSystemService from class ocpp.cs._2015._10.CentralSystemService
[INFO ] 2022-09-05 14:55:19,568 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemServiceOCPP16
[INFO ] 2022-09-05 14:55:19,571 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2010/08/}CentralSystemService from class ocpp.cs._2010._08.CentralSystemService
[INFO ] 2022-09-05 14:55:19,594 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemService
[INFO ] 2022-09-05 14:55:30,058 org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 6.1.7.Final
[WARN ] 2022-09-05 14:55:31,479 org.springframework.security.config.annotation.web.builders.WebSecurity - You are asking Spring Security to ignore Ant [pattern='/static/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
[INFO ] 2022-09-05 14:55:31,489 org.springframework.security.web.DefaultSecurityFilterChain - Will secure Ant [pattern='/static/**'] with []
[WARN ] 2022-09-05 14:55:31,492 org.springframework.security.config.annotation.web.builders.WebSecurity - You are asking Spring Security to ignore Ant [pattern='/views/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
[INFO ] 2022-09-05 14:55:31,492 org.springframework.security.web.DefaultSecurityFilterChain - Will secure Ant [pattern='/views/**'] with []
[INFO ] 2022-09-05 14:55:31,666 org.springframework.security.web.DefaultSecurityFilterChain - Will not secure any request
[INFO ] 2022-09-05 14:55:32,486 org.springframework.web.context.ContextLoader - Root WebApplicationContext initialized in 26715 ms
[INFO ] 2022-09-05 14:55:32,780 org.eclipse.jetty.server.handler.ContextHandler.steve - Initializing Spring DispatcherServlet 'spring-dispatcher'
[INFO ] 2022-09-05 14:55:32,780 org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'spring-dispatcher'
[INFO ] 2022-09-05 14:55:32,783 org.springframework.web.servlet.DispatcherServlet - Completed initialization in 3 ms
[INFO ] 2022-09-05 14:55:32,884 org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@4089713{/steve,jar:file:/home/aryan/steve-steve-3.4.9/target/steve.jar!/webapp,AVAILABLE}
[INFO ] 2022-09-05 14:55:32,945 org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@5290945e{HTTP/1.1, (http/1.1)}{127.0.0.1:8080}
[INFO ] 2022-09-05 14:55:32,961 org.eclipse.jetty.server.Server - Started Server@2c88b9fc{STARTING}[10.0.7,sto=5000] @33538ms
[ERROR] 2022-09-05 15:00:26,081 de.rwth.idsg.steve.ocpp.ws.OcppWebSocketHandshakeHandler - ChargeBoxId '(chargeBoxId)' is not recognized.
[ERROR] 2022-09-05 15:00:44,709 de.rwth.idsg.steve.ocpp.ws.OcppWebSocketHandshakeHandler - No protocol (OCPP version) is specified.
[WARN ] 2022-09-05 15:51:27,661 org.eclipse.jetty.server.HttpChannel - handleException /steve/static/css/style.css java.io.FileNotFoundException: ServletContext resource [/static/css/style.css] cannot be resolved in the file system for checking its last-modified timestamp
[WARN ] 2022-09-05 15:51:27,722 org.eclipse.jetty.server.HttpChannel - handleException /steve/static/images/logo_i5.png java.io.FileNotFoundException: ServletContext resource [/static/images/logo_i5.png] cannot be resolved in the file system for checking its last-modified timestamp
[WARN ] 2022-09-05 15:51:27,668 org.eclipse.jetty.server.HttpChannel - handleException /steve/static/images/logo2.png java.io.FileNotFoundException: ServletContext resource [/static/images/logo2.png] cannot be resolved in the file system for checking its last-modified timestamp
[WARN ] 2022-09-05 15:51:27,735 org.eclipse.jetty.server.HttpChannel - handleException /steve/static/images/logo_rwth.png java.io.FileNotFoundException: ServletContext resource [/static/images/logo_rwth.png] cannot be resolved in the file system for checking its last-modified timestamp
[WARN ] 2022-09-05 15:51:27,975 org.eclipse.jetty.server.HttpChannel - handleException /steve/static/images/favicon.ico java.io.FileNotFoundException: ServletContext resource [/static/images/favicon.ico] cannot be resolved in the file system for checking its last-modified timestamp
[WARN ] 2022-09-05 15:51:28,044 org.eclipse.jetty.server.HttpChannel - handleException /steve/static/images/favicon.ico java.io.FileNotFoundException: ServletContext resource [/static/images/favicon.ico] cannot be resolved in the file system for checking its last-modified timestamp
[INFO ] 2022-09-05 16:00:22,107 org.eclipse.jetty.server.Server - Stopped Server@2c88b9fc{STOPPING}[10.0.7,sto=5000]
[INFO ] 2022-09-05 16:00:22,108 org.eclipse.jetty.server.Server - Shutdown Server@2c88b9fc{STOPPING}[10.0.7,sto=5000]
[INFO ] 2022-09-05 16:00:22,130 org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@5290945e{HTTP/1.1, (http/1.1)}{127.0.0.1:8080}
[INFO ] 2022-09-05 16:00:22,183 org.eclipse.jetty.server.handler.ContextHandler.steve - Destroying Spring FrameworkServlet 'spring-dispatcher'
[INFO ] 2022-09-05 16:00:22,269 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
[INFO ] 2022-09-05 16:00:22,328 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 11.0.16+8-post-Ubuntu-0ubuntu120.04
[INFO ] 2022-09-05 15:55:01,300 org.eclipse.jetty.server.session - DefaultSessionIdManager workerName=node0
[INFO ] 2022-09-05 15:55:01,300 org.eclipse.jetty.server.session - No SessionScavenger set, using defaults
[INFO ] 2022-09-05 15:55:01,304 org.eclipse.jetty.server.session - node0 Scavenging every 600000ms
[INFO ] 2022-09-05 15:55:01,326 org.eclipse.jetty.server.handler.ContextHandler.steve - Initializing Spring root WebApplicationContext
[INFO ] 2022-09-05 15:55:01,327 org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
[INFO ] 2022-09-05 15:55:04,531 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[INFO ] 2022-09-05 15:55:05,219 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[INFO ] 2022-09-05 15:55:11,514 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2010/08/}CentralSystemService from class ocpp.cs._2010._08.CentralSystemService
[INFO ] 2022-09-05 15:55:12,761 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemServiceOCPP12
[INFO ] 2022-09-05 15:55:12,816 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2012/06/}CentralSystemService from class ocpp.cs._2012._06.CentralSystemService
[INFO ] 2022-09-05 15:55:13,081 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemServiceOCPP15
[INFO ] 2022-09-05 15:55:13,087 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2015/10/}CentralSystemService from class ocpp.cs._2015._10.CentralSystemService
[INFO ] 2022-09-05 15:55:13,280 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemServiceOCPP16
[INFO ] 2022-09-05 15:55:13,285 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2010/08/}CentralSystemService from class ocpp.cs._2010._08.CentralSystemService
[INFO ] 2022-09-05 15:55:13,304 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemService
[WARN ] 2022-09-05 15:56:00,959 org.springframework.http.converter.json.Jackson2ObjectMapperBuilder - For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
[INFO ] 2022-09-05 15:56:01,099 org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 6.1.7.Final
[INFO ] 2022-09-05 15:56:02,018 org.springframework.security.web.DefaultSecurityFilterChain - Will secure Ant [pattern='/static/**'] with []
[INFO ] 2022-09-05 15:56:02,019 org.springframework.security.web.DefaultSecurityFilterChain - Will secure Ant [pattern='/views/**'] with []
[INFO ] 2022-09-05 15:56:02,125 org.springframework.security.web.DefaultSecurityFilterChain - Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@708f238f, org.springframework.security.web.context.SecurityContextPersistenceFilter@7212d3df, org.springframework.security.web.header.HeaderWriterFilter@77f66138, org.springframework.security.web.csrf.CsrfFilter@581cb879, org.springframework.security.web.authentication.logout.LogoutFilter@653c0c9c, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@396a4dea, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@2ef5df8f, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@6ff05f85, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@1142843c, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@509d999c, org.springframework.security.web.session.SessionManagementFilter@12ce659, org.springframework.security.web.access.ExceptionTranslationFilter@1f4d9c7f, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@4c0989f7]
[INFO ] 2022-09-05 15:56:02,810 org.springframework.web.context.ContextLoader - Root WebApplicationContext initialized in 61483 ms
[INFO ] 2022-09-05 15:56:03,046 org.eclipse.jetty.server.handler.ContextHandler.steve - Initializing Spring DispatcherServlet 'spring-dispatcher'
[INFO ] 2022-09-05 15:56:03,046 org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'spring-dispatcher'
[INFO ] 2022-09-05 15:56:03,048 org.springframework.web.servlet.DispatcherServlet - Completed initialization in 2 ms
[INFO ] 2022-09-05 15:56:03,102 org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@1df8ea34{/steve,jar:file:/home/aryan/steve-steve-3.4.5/target/steve.jar!/webapp,AVAILABLE}
[ERROR] 2022-09-05 15:56:03,110 de.rwth.idsg.steve.SteveProdStarter - Exception happened
java.io.IOException: Failed to bind to /127.0.0.1:8080 

------------------------------------------------------------------------------------------------------------------------

MariaDB [stevedb]> select * from charge_box;
+---------------+---------------+------------------+---------------+---------------------+---------------------+--------------------+----------------------------+--------------------------+------------+------------------+---------------------+-------+------+------------+---------------------+--------------------+-----------------------+--------------------------+-------------+------+-------------------+--------------------+------------+---------------+-----------------------------------------------+
| charge_box_pk | charge_box_id | endpoint_address | ocpp_protocol | registration_status | charge_point_vendor | charge_point_model | charge_point_serial_number | charge_box_serial_number | fw_version | fw_update_status | fw_update_timestamp | iccid | imsi | meter_type | meter_serial_number | diagnostics_status | diagnostics_timestamp | last_heartbeat_timestamp | description | note | location_latitude | location_longitude | address_pk | admin_address | insert_connector_status_after_transaction_msg |
+---------------+---------------+------------------+---------------+---------------------+---------------------+--------------------+----------------------------+--------------------------+------------+------------------+---------------------+-------+------+------------+---------------------+--------------------+-----------------------+--------------------------+-------------+------+-------------------+--------------------+------------+---------------+-----------------------------------------------+
|             2 | charger       | NULL             | NULL          | Accepted            | NULL                | NULL               | NULL                       | NULL                     | NULL       | NULL             | NULL                | NULL  | NULL | NULL       | NULL                | NULL               | NULL                  | NULL                     | NULL        | NULL |              NULL |               NULL |          2 | NULL          |                                             1 |
+---------------+---------------+------------------+---------------+---------------------+---------------------+--------------------+----------------------------+--------------------------+------------+------------------+---------------------+-------+------+------------+---------------------+--------------------+-----------------------+--------------------------+-------------+------+-------------------+--------------------+------------+---------------+-----------------------------------------------+
1 row in set (0.000 sec)

@goekay Please help.

**Comment by goekay** [comment]
```
[ERROR] 2022-09-05 15:00:26,081 de.rwth.idsg.steve.ocpp.ws.OcppWebSocketHandshakeHandler - ChargeBoxId '(chargeBoxId)' is not recognized.
[ERROR] 2022-09-05 15:00:44,709 de.rwth.idsg.steve.ocpp.ws.OcppWebSocketHandshakeHandler - No protocol (OCPP version) is specified.
```

you will not be able to connect to steve via chrome. there are ocpp specific headers needed in the initial request. please see older issues.
