### ISSUE TITLE
Whitespace support in ChangeConfiguration.req - CTEP

### ISSUE THREAD

**Issue by andle** [steve-community/steve#920]
#### Checklist

- [ x] I checked other issues already, but found no answer/solution
- [ x] I checked the documentation and wiki, but found no answer/solution
- [ x] I am running the latest version and the issue still occurs
- [ x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.9 (trying to build latest)
Operating system  : Raspbian GNU/Linux 10 (buster)
JDK               : 11.0.16
Database          : mariadb  Ver 15.1 Distrib 10.3.34-MariaDB
```

#### Expected Behavior

As per OCA whitepaper regarding CTEP pricing (https://www.openchargealliance.org/uploads/files/ocpp_and_dms_evse_regulation-v2.0.pdf), section 3.1.1 for DefaultPrice, there is implication that whitespace is allowed for ChangeConfiguration.req, especially as its "value" field is of type CiString500Type (I imagine spaces are part of string). See the example call in that section to see whitespace in the strings sent.

#### Actual Behavior

Whitespace not allowed in ChangeConfiguration.req 

#### Steps to Reproduce the Problem

  1. Operations > OCPP 1.6 > ChangeConfiguration
  2. Key Type = Custom, Custom Config Key = <anything>, value = _string with whitespace_
  3. Error message "Value cannot contain any whitespace"

#### Additional context

I am aware of https://github.com/steve-community/steve/issues/148, but that was a different issue. I think whitespace needs to be allowed here, while a different approach for an empty field can be used.

**Comment by goekay** [comment]
thanks for the request. i am removing validation for the value field entirely.
