### ISSUE TITLE
Required paid support on the project, ready to pay

### ISSUE THREAD

**Issue by parvesh-shadow** [steve-community/steve#929]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : ...
Operating system  : ...
JDK               : ...
Database          : ...
```

#### Expected Behavior

...

#### Actual Behavior

...

#### Steps to Reproduce the Problem

  1. ...
  2. ...
  3. ...

#### Additional context
It is a good project. 
I am looking for a developer who have experience on this code. Who has successfully implemented the project?
We are getting few bugs and challenges in customisations. 
Ready to pay for the support?
...

**Comment by rahulbhat13** [comment]
Can contact and suggest the support required

**Comment by parvesh-shadow** [comment]
@rahulbhat13 if you have previous experience and capable to work mail me pksaini1990@gmail.com

**Comment by goekay** [comment]
i consider this issue resolved, and am closing it.
