### ISSUE TITLE
How to Configure steve-steve-3.4.9/src/main/resources/config/prod/main.properties  file to use it for Secure Websocket connection.Can someone please help me with this.

### ISSUE THREAD

**Issue by PavanGitt** [steve-community/steve#930]

**Comment by goekay** [comment]
if you enable https and set up keystore with certificates, you can use `wss://` instead of `ws://`

**Comment by PavanGitt** [comment]
One more thing want to confirm is 
keystore.path - Is this the path of certificate ?
keystore.password- What to provide here?

Any other things that need to be changed for secure websocket connection from Steve side.
If any please add.
Thanks in advance.

**Comment by goekay** [comment]
please use google for keystore info and tutorials. it's the standard way to deal with certificates in the java world.

> Any other things that need to be changed for secure websocket connection from Steve side.

nothing comes to my mind right now. obviously, the station should have/know the certificates as well for the https handshake to be successful.
