### ISSUE TITLE
Does Steve support TLS1.3 ?

### ISSUE THREAD

**Issue by PavanGitt** [steve-community/steve#954]
#### Checklist

I'm able to build steve securely (https) by enabling https =true and providing keystore certificates.

Which version of TLS does Steve is supporting?

While trying to connect with that steve using Websockets im facing an error.

ERROR:websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401.
 
Is this error due to TLS1.3?

#### Specifications
```
SteVe Version     : 3.4.9
Operating system  : Linux Ubuntu(18.04 LTS)
JDK               : 11.0.16
Database          : mysql 15.1 Distrib 10.4.26-MariaDB 

Description:
My intension is to access https steve server using Websocket from my application. While doing so, im facing above exception.

Any suggestions or inputs why i am facing this.
Thanks in Advance.

**Comment by goekay** [comment]
is the chargebox id in database? if not, steve responds with 401 unauthorized.
