### ISSUE TITLE
Limit power consumtption (kWh) for OCCP users

### ISSUE THREAD

**Issue by mare1901** [steve-community/steve#961]
#### Checklist

- [X] I checked other issues already and found no answer
- [X] I checked the documentation and found no answer
- [x] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

...

#### Describe the solution you'd like
I would like to limit the power consumption (kWh) for the ocpp users. Is this possible?
Or is it only possible with the duration in the charging profile section?
...

#### Describe alternative solutions or features you've considered 

...

#### Additional context

...

**Comment by goekay** [comment]
yes, this can be done generally with the "charging profile" feature.
