### ISSUE TITLE
package jooq.steve.db.XXX does not exist

### ISSUE THREAD

**Issue by iayun** [steve-community/steve#989]
#### Checklist

- [ ] I checked other issues already, but found no answer/solution
- [ ] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : ...
Operating system  : ...
JDK               : ...
Database          : ...
```

#### Expected Behavior

...

#### Actual Behavior

...

#### Steps to Reproduce the Problem

  1. maven build
  2. ...
  3. ...

#### Additional context

...

**Comment by goekay** [comment]
pls make sure that the build can access the database.

**Comment by iayun** [comment]
![image](https://user-images.githubusercontent.com/42887310/206601298-060a1fed-6f9e-41cd-988e-803faa45d109.png)
not only database; is the package

**Comment by iayun** [comment]
![image](https://user-images.githubusercontent.com/42887310/206601641-979fba5c-dbd1-4929-a4fb-80ea9294d84c.png)
![image](https://user-images.githubusercontent.com/42887310/206601668-e77a0d25-023e-4a23-84a2-009b99fed968.png)

not only database; is the package

**Comment by goekay** [comment]
pls search within the previous issues. we had similar questions.
